// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.0--rc1
// source: api/artwork/v1/artwork.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArtworkService_CreateArtwork_FullMethodName = "/artwork.v1.ArtworkService/CreateArtwork"
	ArtworkService_UpdateArtwork_FullMethodName = "/artwork.v1.ArtworkService/UpdateArtwork"
	ArtworkService_DeleteArtwork_FullMethodName = "/artwork.v1.ArtworkService/DeleteArtwork"
	ArtworkService_GetArtwork_FullMethodName    = "/artwork.v1.ArtworkService/GetArtwork"
	ArtworkService_SearchArtwork_FullMethodName = "/artwork.v1.ArtworkService/SearchArtwork"
	ArtworkService_UploadImage_FullMethodName   = "/artwork.v1.ArtworkService/UploadImage"
)

// ArtworkServiceClient is the client API for ArtworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 画作服务
type ArtworkServiceClient interface {
	// 创建画作
	CreateArtwork(ctx context.Context, in *CreateArtworkRequest, opts ...grpc.CallOption) (*CreateArtworkReply, error)
	// 更新画作
	UpdateArtwork(ctx context.Context, in *UpdateArtworkRequest, opts ...grpc.CallOption) (*UpdateArtworkReply, error)
	// 删除画作（软删除）
	DeleteArtwork(ctx context.Context, in *DeleteArtworkRequest, opts ...grpc.CallOption) (*DeleteArtworkReply, error)
	// 获取画作详情
	GetArtwork(ctx context.Context, in *GetArtworkRequest, opts ...grpc.CallOption) (*GetArtworkReply, error)
	// 搜索画作
	SearchArtwork(ctx context.Context, in *SearchArtworkRequest, opts ...grpc.CallOption) (*SearchArtworkReply, error)
	// 上传图片
	UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageReply, error)
}

type artworkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArtworkServiceClient(cc grpc.ClientConnInterface) ArtworkServiceClient {
	return &artworkServiceClient{cc}
}

func (c *artworkServiceClient) CreateArtwork(ctx context.Context, in *CreateArtworkRequest, opts ...grpc.CallOption) (*CreateArtworkReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateArtworkReply)
	err := c.cc.Invoke(ctx, ArtworkService_CreateArtwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artworkServiceClient) UpdateArtwork(ctx context.Context, in *UpdateArtworkRequest, opts ...grpc.CallOption) (*UpdateArtworkReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateArtworkReply)
	err := c.cc.Invoke(ctx, ArtworkService_UpdateArtwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artworkServiceClient) DeleteArtwork(ctx context.Context, in *DeleteArtworkRequest, opts ...grpc.CallOption) (*DeleteArtworkReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteArtworkReply)
	err := c.cc.Invoke(ctx, ArtworkService_DeleteArtwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artworkServiceClient) GetArtwork(ctx context.Context, in *GetArtworkRequest, opts ...grpc.CallOption) (*GetArtworkReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArtworkReply)
	err := c.cc.Invoke(ctx, ArtworkService_GetArtwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artworkServiceClient) SearchArtwork(ctx context.Context, in *SearchArtworkRequest, opts ...grpc.CallOption) (*SearchArtworkReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchArtworkReply)
	err := c.cc.Invoke(ctx, ArtworkService_SearchArtwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artworkServiceClient) UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadImageReply)
	err := c.cc.Invoke(ctx, ArtworkService_UploadImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtworkServiceServer is the server API for ArtworkService service.
// All implementations must embed UnimplementedArtworkServiceServer
// for forward compatibility.
//
// 画作服务
type ArtworkServiceServer interface {
	// 创建画作
	CreateArtwork(context.Context, *CreateArtworkRequest) (*CreateArtworkReply, error)
	// 更新画作
	UpdateArtwork(context.Context, *UpdateArtworkRequest) (*UpdateArtworkReply, error)
	// 删除画作（软删除）
	DeleteArtwork(context.Context, *DeleteArtworkRequest) (*DeleteArtworkReply, error)
	// 获取画作详情
	GetArtwork(context.Context, *GetArtworkRequest) (*GetArtworkReply, error)
	// 搜索画作
	SearchArtwork(context.Context, *SearchArtworkRequest) (*SearchArtworkReply, error)
	// 上传图片
	UploadImage(context.Context, *UploadImageRequest) (*UploadImageReply, error)
	mustEmbedUnimplementedArtworkServiceServer()
}

// UnimplementedArtworkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArtworkServiceServer struct{}

func (UnimplementedArtworkServiceServer) CreateArtwork(context.Context, *CreateArtworkRequest) (*CreateArtworkReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateArtwork not implemented")
}
func (UnimplementedArtworkServiceServer) UpdateArtwork(context.Context, *UpdateArtworkRequest) (*UpdateArtworkReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateArtwork not implemented")
}
func (UnimplementedArtworkServiceServer) DeleteArtwork(context.Context, *DeleteArtworkRequest) (*DeleteArtworkReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteArtwork not implemented")
}
func (UnimplementedArtworkServiceServer) GetArtwork(context.Context, *GetArtworkRequest) (*GetArtworkReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtwork not implemented")
}
func (UnimplementedArtworkServiceServer) SearchArtwork(context.Context, *SearchArtworkRequest) (*SearchArtworkReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchArtwork not implemented")
}
func (UnimplementedArtworkServiceServer) UploadImage(context.Context, *UploadImageRequest) (*UploadImageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadImage not implemented")
}
func (UnimplementedArtworkServiceServer) mustEmbedUnimplementedArtworkServiceServer() {}
func (UnimplementedArtworkServiceServer) testEmbeddedByValue()                        {}

// UnsafeArtworkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtworkServiceServer will
// result in compilation errors.
type UnsafeArtworkServiceServer interface {
	mustEmbedUnimplementedArtworkServiceServer()
}

func RegisterArtworkServiceServer(s grpc.ServiceRegistrar, srv ArtworkServiceServer) {
	// If the following call panics, it indicates UnimplementedArtworkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArtworkService_ServiceDesc, srv)
}

func _ArtworkService_CreateArtwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArtworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtworkServiceServer).CreateArtwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtworkService_CreateArtwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtworkServiceServer).CreateArtwork(ctx, req.(*CreateArtworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtworkService_UpdateArtwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArtworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtworkServiceServer).UpdateArtwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtworkService_UpdateArtwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtworkServiceServer).UpdateArtwork(ctx, req.(*UpdateArtworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtworkService_DeleteArtwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArtworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtworkServiceServer).DeleteArtwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtworkService_DeleteArtwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtworkServiceServer).DeleteArtwork(ctx, req.(*DeleteArtworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtworkService_GetArtwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtworkServiceServer).GetArtwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtworkService_GetArtwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtworkServiceServer).GetArtwork(ctx, req.(*GetArtworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtworkService_SearchArtwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchArtworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtworkServiceServer).SearchArtwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtworkService_SearchArtwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtworkServiceServer).SearchArtwork(ctx, req.(*SearchArtworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtworkService_UploadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtworkServiceServer).UploadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtworkService_UploadImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtworkServiceServer).UploadImage(ctx, req.(*UploadImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArtworkService_ServiceDesc is the grpc.ServiceDesc for ArtworkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArtworkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "artwork.v1.ArtworkService",
	HandlerType: (*ArtworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateArtwork",
			Handler:    _ArtworkService_CreateArtwork_Handler,
		},
		{
			MethodName: "UpdateArtwork",
			Handler:    _ArtworkService_UpdateArtwork_Handler,
		},
		{
			MethodName: "DeleteArtwork",
			Handler:    _ArtworkService_DeleteArtwork_Handler,
		},
		{
			MethodName: "GetArtwork",
			Handler:    _ArtworkService_GetArtwork_Handler,
		},
		{
			MethodName: "SearchArtwork",
			Handler:    _ArtworkService_SearchArtwork_Handler,
		},
		{
			MethodName: "UploadImage",
			Handler:    _ArtworkService_UploadImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/artwork/v1/artwork.proto",
}
