// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: api/artwork/v1/artwork.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 画作信息
type ArtworkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Width         float64                `protobuf:"fixed64,6,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,7,opt,name=height,proto3" json:"height,omitempty"`
	Material      string                 `protobuf:"bytes,8,opt,name=material,proto3" json:"material,omitempty"`
	Price         float64                `protobuf:"fixed64,9,opt,name=price,proto3" json:"price,omitempty"`
	IsCollected   bool                   `protobuf:"varint,10,opt,name=is_collected,json=isCollected,proto3" json:"is_collected,omitempty"`
	Location      string                 `protobuf:"bytes,11,opt,name=location,proto3" json:"location,omitempty"`
	Style         string                 `protobuf:"bytes,12,opt,name=style,proto3" json:"style,omitempty"`
	Technique     string                 `protobuf:"bytes,13,opt,name=technique,proto3" json:"technique,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,14,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CategoryId    int64                  `protobuf:"varint,15,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,16,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Tags          []string               `protobuf:"bytes,17,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtworkInfo) Reset() {
	*x = ArtworkInfo{}
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtworkInfo) ProtoMessage() {}

func (x *ArtworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtworkInfo.ProtoReflect.Descriptor instead.
func (*ArtworkInfo) Descriptor() ([]byte, []int) {
	return file_api_artwork_v1_artwork_proto_rawDescGZIP(), []int{0}
}

func (x *ArtworkInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArtworkInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArtworkInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ArtworkInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ArtworkInfo) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ArtworkInfo) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ArtworkInfo) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ArtworkInfo) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

func (x *ArtworkInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ArtworkInfo) GetIsCollected() bool {
	if x != nil {
		return x.IsCollected
	}
	return false
}

func (x *ArtworkInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ArtworkInfo) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *ArtworkInfo) GetTechnique() string {
	if x != nil {
		return x.Technique
	}
	return ""
}

func (x *ArtworkInfo) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ArtworkInfo) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ArtworkInfo) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ArtworkInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ArtworkInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ArtworkInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 创建画作请求
type CreateArtworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Width         float64                `protobuf:"fixed64,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,6,opt,name=height,proto3" json:"height,omitempty"`
	Material      string                 `protobuf:"bytes,7,opt,name=material,proto3" json:"material,omitempty"`
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	IsCollected   bool                   `protobuf:"varint,9,opt,name=is_collected,json=isCollected,proto3" json:"is_collected,omitempty"`
	Location      string                 `protobuf:"bytes,10,opt,name=location,proto3" json:"location,omitempty"`
	Style         string                 `protobuf:"bytes,11,opt,name=style,proto3" json:"style,omitempty"`
	Technique     string                 `protobuf:"bytes,12,opt,name=technique,proto3" json:"technique,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,13,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CategoryId    int64                  `protobuf:"varint,14,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Tags          []string               `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArtworkRequest) Reset() {
	*x = CreateArtworkRequest{}
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArtworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtworkRequest) ProtoMessage() {}

func (x *CreateArtworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtworkRequest.ProtoReflect.Descriptor instead.
func (*CreateArtworkRequest) Descriptor() ([]byte, []int) {
	return file_api_artwork_v1_artwork_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArtworkRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArtworkRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateArtworkRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateArtworkRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateArtworkRequest) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CreateArtworkRequest) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CreateArtworkRequest) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

func (x *CreateArtworkRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateArtworkRequest) GetIsCollected() bool {
	if x != nil {
		return x.IsCollected
	}
	return false
}

func (x *CreateArtworkRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateArtworkRequest) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *CreateArtworkRequest) GetTechnique() string {
	if x != nil {
		return x.Technique
	}
	return ""
}

func (x *CreateArtworkRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateArtworkRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateArtworkRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// 创建画作响应
type CreateArtworkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artwork       *ArtworkInfo           `protobuf:"bytes,1,opt,name=artwork,proto3" json:"artwork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArtworkReply) Reset() {
	*x = CreateArtworkReply{}
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArtworkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtworkReply) ProtoMessage() {}

func (x *CreateArtworkReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtworkReply.ProtoReflect.Descriptor instead.
func (*CreateArtworkReply) Descriptor() ([]byte, []int) {
	return file_api_artwork_v1_artwork_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArtworkReply) GetArtwork() *ArtworkInfo {
	if x != nil {
		return x.Artwork
	}
	return nil
}

// 更新画作请求
type UpdateArtworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Width         float64                `protobuf:"fixed64,6,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,7,opt,name=height,proto3" json:"height,omitempty"`
	Material      string                 `protobuf:"bytes,8,opt,name=material,proto3" json:"material,omitempty"`
	Price         float64                `protobuf:"fixed64,9,opt,name=price,proto3" json:"price,omitempty"`
	IsCollected   bool                   `protobuf:"varint,10,opt,name=is_collected,json=isCollected,proto3" json:"is_collected,omitempty"`
	Location      string                 `protobuf:"bytes,11,opt,name=location,proto3" json:"location,omitempty"`
	Style         string                 `protobuf:"bytes,12,opt,name=style,proto3" json:"style,omitempty"`
	Technique     string                 `protobuf:"bytes,13,opt,name=technique,proto3" json:"technique,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,14,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CategoryId    int64                  `protobuf:"varint,15,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Tags          []string               `protobuf:"bytes,16,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArtworkRequest) Reset() {
	*x = UpdateArtworkRequest{}
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArtworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtworkRequest) ProtoMessage() {}

func (x *UpdateArtworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtworkRequest.ProtoReflect.Descriptor instead.
func (*UpdateArtworkRequest) Descriptor() ([]byte, []int) {
	return file_api_artwork_v1_artwork_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateArtworkRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateArtworkRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateArtworkRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateArtworkRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *UpdateArtworkRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *UpdateArtworkRequest) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UpdateArtworkRequest) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UpdateArtworkRequest) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

func (x *UpdateArtworkRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateArtworkRequest) GetIsCollected() bool {
	if x != nil {
		return x.IsCollected
	}
	return false
}

func (x *UpdateArtworkRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateArtworkRequest) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *UpdateArtworkRequest) GetTechnique() string {
	if x != nil {
		return x.Technique
	}
	return ""
}

func (x *UpdateArtworkRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UpdateArtworkRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateArtworkRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// 更新画作响应
type UpdateArtworkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artwork       *ArtworkInfo           `protobuf:"bytes,1,opt,name=artwork,proto3" json:"artwork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArtworkReply) Reset() {
	*x = UpdateArtworkReply{}
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArtworkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtworkReply) ProtoMessage() {}

func (x *UpdateArtworkReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtworkReply.ProtoReflect.Descriptor instead.
func (*UpdateArtworkReply) Descriptor() ([]byte, []int) {
	return file_api_artwork_v1_artwork_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateArtworkReply) GetArtwork() *ArtworkInfo {
	if x != nil {
		return x.Artwork
	}
	return nil
}

// 删除画作请求
type DeleteArtworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtworkRequest) Reset() {
	*x = DeleteArtworkRequest{}
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtworkRequest) ProtoMessage() {}

func (x *DeleteArtworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtworkRequest.ProtoReflect.Descriptor instead.
func (*DeleteArtworkRequest) Descriptor() ([]byte, []int) {
	return file_api_artwork_v1_artwork_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteArtworkRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除画作响应
type DeleteArtworkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtworkReply) Reset() {
	*x = DeleteArtworkReply{}
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtworkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtworkReply) ProtoMessage() {}

func (x *DeleteArtworkReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtworkReply.ProtoReflect.Descriptor instead.
func (*DeleteArtworkReply) Descriptor() ([]byte, []int) {
	return file_api_artwork_v1_artwork_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteArtworkReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取画作请求
type GetArtworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtworkRequest) Reset() {
	*x = GetArtworkRequest{}
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtworkRequest) ProtoMessage() {}

func (x *GetArtworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtworkRequest.ProtoReflect.Descriptor instead.
func (*GetArtworkRequest) Descriptor() ([]byte, []int) {
	return file_api_artwork_v1_artwork_proto_rawDescGZIP(), []int{7}
}

func (x *GetArtworkRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取画作响应
type GetArtworkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artwork       *ArtworkInfo           `protobuf:"bytes,1,opt,name=artwork,proto3" json:"artwork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtworkReply) Reset() {
	*x = GetArtworkReply{}
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtworkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtworkReply) ProtoMessage() {}

func (x *GetArtworkReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtworkReply.ProtoReflect.Descriptor instead.
func (*GetArtworkReply) Descriptor() ([]byte, []int) {
	return file_api_artwork_v1_artwork_proto_rawDescGZIP(), []int{8}
}

func (x *GetArtworkReply) GetArtwork() *ArtworkInfo {
	if x != nil {
		return x.Artwork
	}
	return nil
}

// 搜索画作请求
type SearchArtworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`                           // 关键词（标题、描述、作者）
	YearFrom      int32                  `protobuf:"varint,2,opt,name=year_from,json=yearFrom,proto3" json:"year_from,omitempty"`        // 起始年份
	YearTo        int32                  `protobuf:"varint,3,opt,name=year_to,json=yearTo,proto3" json:"year_to,omitempty"`              // 结束年份
	WidthMin      float64                `protobuf:"fixed64,4,opt,name=width_min,json=widthMin,proto3" json:"width_min,omitempty"`       // 最小宽度
	WidthMax      float64                `protobuf:"fixed64,5,opt,name=width_max,json=widthMax,proto3" json:"width_max,omitempty"`       // 最大宽度
	HeightMin     float64                `protobuf:"fixed64,6,opt,name=height_min,json=heightMin,proto3" json:"height_min,omitempty"`    // 最小高度
	HeightMax     float64                `protobuf:"fixed64,7,opt,name=height_max,json=heightMax,proto3" json:"height_max,omitempty"`    // 最大高度
	PriceMin      float64                `protobuf:"fixed64,8,opt,name=price_min,json=priceMin,proto3" json:"price_min,omitempty"`       // 最低价格
	PriceMax      float64                `protobuf:"fixed64,9,opt,name=price_max,json=priceMax,proto3" json:"price_max,omitempty"`       // 最高价格
	CategoryId    int64                  `protobuf:"varint,10,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // 分类ID
	Tags          []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`                                // 标签列表
	Page          int32                  `protobuf:"varint,12,opt,name=page,proto3" json:"page,omitempty"`                               // 页码（从1开始）
	PageSize      int32                  `protobuf:"varint,13,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       // 每页数量
	SortBy        string                 `protobuf:"bytes,14,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`              // 排序字段（created_at, updated_at, title, price）
	SortOrder     string                 `protobuf:"bytes,15,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`     // 排序方向（asc, desc）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArtworkRequest) Reset() {
	*x = SearchArtworkRequest{}
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArtworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArtworkRequest) ProtoMessage() {}

func (x *SearchArtworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArtworkRequest.ProtoReflect.Descriptor instead.
func (*SearchArtworkRequest) Descriptor() ([]byte, []int) {
	return file_api_artwork_v1_artwork_proto_rawDescGZIP(), []int{9}
}

func (x *SearchArtworkRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchArtworkRequest) GetYearFrom() int32 {
	if x != nil {
		return x.YearFrom
	}
	return 0
}

func (x *SearchArtworkRequest) GetYearTo() int32 {
	if x != nil {
		return x.YearTo
	}
	return 0
}

func (x *SearchArtworkRequest) GetWidthMin() float64 {
	if x != nil {
		return x.WidthMin
	}
	return 0
}

func (x *SearchArtworkRequest) GetWidthMax() float64 {
	if x != nil {
		return x.WidthMax
	}
	return 0
}

func (x *SearchArtworkRequest) GetHeightMin() float64 {
	if x != nil {
		return x.HeightMin
	}
	return 0
}

func (x *SearchArtworkRequest) GetHeightMax() float64 {
	if x != nil {
		return x.HeightMax
	}
	return 0
}

func (x *SearchArtworkRequest) GetPriceMin() float64 {
	if x != nil {
		return x.PriceMin
	}
	return 0
}

func (x *SearchArtworkRequest) GetPriceMax() float64 {
	if x != nil {
		return x.PriceMax
	}
	return 0
}

func (x *SearchArtworkRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *SearchArtworkRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchArtworkRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchArtworkRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchArtworkRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *SearchArtworkRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

// 搜索画作响应
type SearchArtworkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artworks      []*ArtworkInfo         `protobuf:"bytes,1,rep,name=artworks,proto3" json:"artworks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总数
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArtworkReply) Reset() {
	*x = SearchArtworkReply{}
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArtworkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArtworkReply) ProtoMessage() {}

func (x *SearchArtworkReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArtworkReply.ProtoReflect.Descriptor instead.
func (*SearchArtworkReply) Descriptor() ([]byte, []int) {
	return file_api_artwork_v1_artwork_proto_rawDescGZIP(), []int{10}
}

func (x *SearchArtworkReply) GetArtworks() []*ArtworkInfo {
	if x != nil {
		return x.Artworks
	}
	return nil
}

func (x *SearchArtworkReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchArtworkReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchArtworkReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 上传图片请求
type UploadImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                          // 文件名
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                            // 图片内容
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // 内容类型（如 image/jpeg）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_api_artwork_v1_artwork_proto_rawDescGZIP(), []int{11}
}

func (x *UploadImageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadImageRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadImageRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// 上传图片响应
type UploadImageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`           // 图片URL
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"` // 文件名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageReply) Reset() {
	*x = UploadImageReply{}
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageReply) ProtoMessage() {}

func (x *UploadImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_artwork_v1_artwork_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageReply.ProtoReflect.Descriptor instead.
func (*UploadImageReply) Descriptor() ([]byte, []int) {
	return file_api_artwork_v1_artwork_proto_rawDescGZIP(), []int{12}
}

func (x *UploadImageReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadImageReply) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_api_artwork_v1_artwork_proto protoreflect.FileDescriptor

const file_api_artwork_v1_artwork_proto_rawDesc = "" +
	"\n" +
	"\x1capi/artwork/v1/artwork.proto\x12\n" +
	"artwork.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x04\n" +
	"\vArtworkInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x14\n" +
	"\x05width\x18\x06 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\x01R\x06height\x12\x1a\n" +
	"\bmaterial\x18\b \x01(\tR\bmaterial\x12\x14\n" +
	"\x05price\x18\t \x01(\x01R\x05price\x12!\n" +
	"\fis_collected\x18\n" +
	" \x01(\bR\visCollected\x12\x1a\n" +
	"\blocation\x18\v \x01(\tR\blocation\x12\x14\n" +
	"\x05style\x18\f \x01(\tR\x05style\x12\x1c\n" +
	"\ttechnique\x18\r \x01(\tR\ttechnique\x12\x1b\n" +
	"\timage_url\x18\x0e \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vcategory_id\x18\x0f \x01(\x03R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x10 \x01(\tR\fcategoryName\x12\x12\n" +
	"\x04tags\x18\x11 \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9f\x03\n" +
	"\x14CreateArtworkRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x01R\x06height\x12\x1a\n" +
	"\bmaterial\x18\a \x01(\tR\bmaterial\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12!\n" +
	"\fis_collected\x18\t \x01(\bR\visCollected\x12\x1a\n" +
	"\blocation\x18\n" +
	" \x01(\tR\blocation\x12\x14\n" +
	"\x05style\x18\v \x01(\tR\x05style\x12\x1c\n" +
	"\ttechnique\x18\f \x01(\tR\ttechnique\x12\x1b\n" +
	"\timage_url\x18\r \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vcategory_id\x18\x0e \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04tags\x18\x0f \x03(\tR\x04tags\"G\n" +
	"\x12CreateArtworkReply\x121\n" +
	"\aartwork\x18\x01 \x01(\v2\x17.artwork.v1.ArtworkInfoR\aartwork\"\xaf\x03\n" +
	"\x14UpdateArtworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x14\n" +
	"\x05width\x18\x06 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\x01R\x06height\x12\x1a\n" +
	"\bmaterial\x18\b \x01(\tR\bmaterial\x12\x14\n" +
	"\x05price\x18\t \x01(\x01R\x05price\x12!\n" +
	"\fis_collected\x18\n" +
	" \x01(\bR\visCollected\x12\x1a\n" +
	"\blocation\x18\v \x01(\tR\blocation\x12\x14\n" +
	"\x05style\x18\f \x01(\tR\x05style\x12\x1c\n" +
	"\ttechnique\x18\r \x01(\tR\ttechnique\x12\x1b\n" +
	"\timage_url\x18\x0e \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vcategory_id\x18\x0f \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04tags\x18\x10 \x03(\tR\x04tags\"G\n" +
	"\x12UpdateArtworkReply\x121\n" +
	"\aartwork\x18\x01 \x01(\v2\x17.artwork.v1.ArtworkInfoR\aartwork\"&\n" +
	"\x14DeleteArtworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\".\n" +
	"\x12DeleteArtworkReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x11GetArtworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"D\n" +
	"\x0fGetArtworkReply\x121\n" +
	"\aartwork\x18\x01 \x01(\v2\x17.artwork.v1.ArtworkInfoR\aartwork\"\xb6\x03\n" +
	"\x14SearchArtworkRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x1b\n" +
	"\tyear_from\x18\x02 \x01(\x05R\byearFrom\x12\x17\n" +
	"\ayear_to\x18\x03 \x01(\x05R\x06yearTo\x12\x1b\n" +
	"\twidth_min\x18\x04 \x01(\x01R\bwidthMin\x12\x1b\n" +
	"\twidth_max\x18\x05 \x01(\x01R\bwidthMax\x12\x1d\n" +
	"\n" +
	"height_min\x18\x06 \x01(\x01R\theightMin\x12\x1d\n" +
	"\n" +
	"height_max\x18\a \x01(\x01R\theightMax\x12\x1b\n" +
	"\tprice_min\x18\b \x01(\x01R\bpriceMin\x12\x1b\n" +
	"\tprice_max\x18\t \x01(\x01R\bpriceMax\x12\x1f\n" +
	"\vcategory_id\x18\n" +
	" \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x12\x12\n" +
	"\x04page\x18\f \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\r \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x0e \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x0f \x01(\tR\tsortOrder\"\x90\x01\n" +
	"\x12SearchArtworkReply\x123\n" +
	"\bartworks\x18\x01 \x03(\v2\x17.artwork.v1.ArtworkInfoR\bartworks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"m\n" +
	"\x12UploadImageRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"@\n" +
	"\x10UploadImageReply\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename2\xc7\x05\n" +
	"\x0eArtworkService\x12q\n" +
	"\rCreateArtwork\x12 .artwork.v1.CreateArtworkRequest\x1a\x1e.artwork.v1.CreateArtworkReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/artwork/artwork\x12v\n" +
	"\rUpdateArtwork\x12 .artwork.v1.UpdateArtworkRequest\x1a\x1e.artwork.v1.UpdateArtworkReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/v1/artwork/artwork/{id}\x12s\n" +
	"\rDeleteArtwork\x12 .artwork.v1.DeleteArtworkRequest\x1a\x1e.artwork.v1.DeleteArtworkReply\" \x82\xd3\xe4\x93\x02\x1a*\x18/v1/artwork/artwork/{id}\x12j\n" +
	"\n" +
	"GetArtwork\x12\x1d.artwork.v1.GetArtworkRequest\x1a\x1b.artwork.v1.GetArtworkReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/artwork/artwork/{id}\x12u\n" +
	"\rSearchArtwork\x12 .artwork.v1.SearchArtworkRequest\x1a\x1e.artwork.v1.SearchArtworkReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/artwork/artwork/search\x12r\n" +
	"\vUploadImage\x12\x1e.artwork.v1.UploadImageRequest\x1a\x1c.artwork.v1.UploadImageReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/artwork/artwork/uploadBH\n" +
	"\x19dev.kratos.api.artwork.v1B\x0eArtworkProtoV1P\x01Z\x19artwork/api/artwork/v1;v1b\x06proto3"

var (
	file_api_artwork_v1_artwork_proto_rawDescOnce sync.Once
	file_api_artwork_v1_artwork_proto_rawDescData []byte
)

func file_api_artwork_v1_artwork_proto_rawDescGZIP() []byte {
	file_api_artwork_v1_artwork_proto_rawDescOnce.Do(func() {
		file_api_artwork_v1_artwork_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_artwork_v1_artwork_proto_rawDesc), len(file_api_artwork_v1_artwork_proto_rawDesc)))
	})
	return file_api_artwork_v1_artwork_proto_rawDescData
}

var file_api_artwork_v1_artwork_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_artwork_v1_artwork_proto_goTypes = []any{
	(*ArtworkInfo)(nil),           // 0: artwork.v1.ArtworkInfo
	(*CreateArtworkRequest)(nil),  // 1: artwork.v1.CreateArtworkRequest
	(*CreateArtworkReply)(nil),    // 2: artwork.v1.CreateArtworkReply
	(*UpdateArtworkRequest)(nil),  // 3: artwork.v1.UpdateArtworkRequest
	(*UpdateArtworkReply)(nil),    // 4: artwork.v1.UpdateArtworkReply
	(*DeleteArtworkRequest)(nil),  // 5: artwork.v1.DeleteArtworkRequest
	(*DeleteArtworkReply)(nil),    // 6: artwork.v1.DeleteArtworkReply
	(*GetArtworkRequest)(nil),     // 7: artwork.v1.GetArtworkRequest
	(*GetArtworkReply)(nil),       // 8: artwork.v1.GetArtworkReply
	(*SearchArtworkRequest)(nil),  // 9: artwork.v1.SearchArtworkRequest
	(*SearchArtworkReply)(nil),    // 10: artwork.v1.SearchArtworkReply
	(*UploadImageRequest)(nil),    // 11: artwork.v1.UploadImageRequest
	(*UploadImageReply)(nil),      // 12: artwork.v1.UploadImageReply
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_api_artwork_v1_artwork_proto_depIdxs = []int32{
	13, // 0: artwork.v1.ArtworkInfo.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: artwork.v1.ArtworkInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: artwork.v1.CreateArtworkReply.artwork:type_name -> artwork.v1.ArtworkInfo
	0,  // 3: artwork.v1.UpdateArtworkReply.artwork:type_name -> artwork.v1.ArtworkInfo
	0,  // 4: artwork.v1.GetArtworkReply.artwork:type_name -> artwork.v1.ArtworkInfo
	0,  // 5: artwork.v1.SearchArtworkReply.artworks:type_name -> artwork.v1.ArtworkInfo
	1,  // 6: artwork.v1.ArtworkService.CreateArtwork:input_type -> artwork.v1.CreateArtworkRequest
	3,  // 7: artwork.v1.ArtworkService.UpdateArtwork:input_type -> artwork.v1.UpdateArtworkRequest
	5,  // 8: artwork.v1.ArtworkService.DeleteArtwork:input_type -> artwork.v1.DeleteArtworkRequest
	7,  // 9: artwork.v1.ArtworkService.GetArtwork:input_type -> artwork.v1.GetArtworkRequest
	9,  // 10: artwork.v1.ArtworkService.SearchArtwork:input_type -> artwork.v1.SearchArtworkRequest
	11, // 11: artwork.v1.ArtworkService.UploadImage:input_type -> artwork.v1.UploadImageRequest
	2,  // 12: artwork.v1.ArtworkService.CreateArtwork:output_type -> artwork.v1.CreateArtworkReply
	4,  // 13: artwork.v1.ArtworkService.UpdateArtwork:output_type -> artwork.v1.UpdateArtworkReply
	6,  // 14: artwork.v1.ArtworkService.DeleteArtwork:output_type -> artwork.v1.DeleteArtworkReply
	8,  // 15: artwork.v1.ArtworkService.GetArtwork:output_type -> artwork.v1.GetArtworkReply
	10, // 16: artwork.v1.ArtworkService.SearchArtwork:output_type -> artwork.v1.SearchArtworkReply
	12, // 17: artwork.v1.ArtworkService.UploadImage:output_type -> artwork.v1.UploadImageReply
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_artwork_v1_artwork_proto_init() }
func file_api_artwork_v1_artwork_proto_init() {
	if File_api_artwork_v1_artwork_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_artwork_v1_artwork_proto_rawDesc), len(file_api_artwork_v1_artwork_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_artwork_v1_artwork_proto_goTypes,
		DependencyIndexes: file_api_artwork_v1_artwork_proto_depIdxs,
		MessageInfos:      file_api_artwork_v1_artwork_proto_msgTypes,
	}.Build()
	File_api_artwork_v1_artwork_proto = out.File
	file_api_artwork_v1_artwork_proto_goTypes = nil
	file_api_artwork_v1_artwork_proto_depIdxs = nil
}
