// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"artwork/internal/biz"
	"artwork/internal/conf"
	"artwork/internal/data"
	"artwork/internal/server"
	"artwork/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	artworkRepo := data.NewArtworkRepo(dataData, logger)
	categoryRepo := data.NewCategoryRepo(dataData, logger)
	tagRepo := data.NewTagRepo(dataData, logger)
	string2 := data.NewBucketName(confData)
	imageRepo := data.NewImageRepo(dataData, string2, logger)
	artworkUsecase := biz.NewArtworkUsecase(artworkRepo, categoryRepo, tagRepo, imageRepo, string2, logger)
	artworkService := service.NewArtworkService(artworkUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, artworkService, logger)
	httpServer := server.NewHTTPServer(confServer, artworkService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
