// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"artwork/internal/biz"
	"artwork/internal/conf"
	"artwork/internal/data"
	"artwork/internal/server"
	"artwork/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	artworkRepo := data.NewArtworkRepo(dataData, logger)
	categoryRepo := data.NewCategoryRepo(dataData, logger)
	tagRepo := data.NewTagRepo(dataData, logger)
	bucketName := data.NewBucketName(confData)
	imageRepo := data.NewImageRepo(dataData, bucketName, logger)
	artworkUsecase := biz.NewArtworkUsecase(artworkRepo, categoryRepo, tagRepo, imageRepo, bucketName, logger)
	artworkService := service.NewArtworkService(artworkUsecase, logger)

	rdb := data.NewRedisClient(dataData)
	authRedisRepo := data.NewAuthRedisRepo(rdb)
	db := data.NewDB(dataData)
	userDataRepo := data.NewUserDataRepo(db, logger)
	tokenManager, err := data.NewTokenManager(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authUsecase := biz.NewAuthUsecase(userDataRepo, authRedisRepo, tokenManager, logger)
	authService := service.NewAuthService(authUsecase, logger)
	userUsecase := biz.NewUserUsecase(userDataRepo, categoryRepo, logger)
	userService := service.NewUserService(userUsecase, logger)

	authMiddleware := server.NewAuthMiddleware(tokenManager)

	grpcServer := server.NewGRPCServer(confServer, artworkService, authService, userService, authMiddleware, logger)
	httpServer := server.NewHTTPServer(confServer, artworkService, authService, userService, dataData, bucketName, authMiddleware, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
