server:
  http:
    addr: 0.0.0.0:32800
    timeout: 1s
  grpc:
    addr: 0.0.0.0:33800
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/artwork?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    network: tcp
    addr: 127.0.0.1:6379
    password: ""
    db: 0
    read_timeout: 999s
    write_timeout: 999s
  minio:
    endpoint: 127.0.0.1:9000
    access_key_id: minioadmin
    secret_access_key: minioadmin
    use_ssl: false
    bucket_name: artwork
  auth:
    jwt_secret: artwork-dev-secret
    access_token_expire: 2h
    refresh_token_expire: 168h
